### ISSUE TITLE
Nefungují IPR ortofotomapy

### ISSUE THREAD

**Issue by PetrDlouhy** [auto-mat/prahounakole#30]
Nefunguje vrstva "Ortofoto IPR" a "Ortofoto IPR mimovegetační". Zřejmě se změnily URL adresy zdroje těch map.
Našel jsem, že IPR provozuje nějakou tilovací službu tady: https://gs-pub.praha.eu/imgs/rest/services/ort/letecke_snimkovani/ImageServer/

**Comment by tmszi** [comment]
> Nefunguje vrstva "Ortofoto IPR" a "Ortofoto IPR mimovegetační". Zřejmě se změnily URL adresy zdroje těch map. Našel jsem, že IPR provozuje nějakou tilovací službu tady: https://gs-pub.praha.eu/imgs/rest/services/ort/letecke_snimkovani/ImageServer/

Pozriem sa na to.
